name: deploy

on:
  push:
    branches:
      - main

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: "setup node"
          uses: actions/setup-node@v2
          with:
            node-version: 16
        - name: "install pnpm"
          run: npm install -g pnpm
        - name: "install dependencies"
          run: pnpm install --no-frozen-lockfile
        - name: "build"
          run: pnpm docs:build
        - name: "deploy"
          uses: SamKirkland/FTP-Deploy-Action@4.2.0
          with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: docs/.vitepress/dist/
